In [ ]:
pip install mysql-connector-python

In [ ]:
import mysql.connector

# Remplacez les valeurs suivantes par les informations de connexion à votre serveur MySQL
host = "localhost" # L'hôte du serveur MySQL
user = "root"  # Votre nom d'utilisateur MySQL
password = "root"  # Votre mot de passe MySQL
database_name = "courses"  # Le nom de la nouvelle base de données



# Créez une connexion au serveur MySQL
conn = mysql.connector.connect(
    host=host,
    user=user,
    password=password
)

# Créez un curseur pour exécuter des requêtes SQL
cursor = conn.cursor()

# Exécutez une requête SQL pour obtenir la liste des bases de données
cursor.execute("SHOW DATABASES")

# Récupérez les résultats de la requête
databases = cursor.fetchall()

# Vérifiez si la base de données que vous recherchez existe
if (database_name,) in databases:
    print(f"La base de données '{database_name}' existe.")
else:
    print(f"La base de données '{database_name}' n'existe pas.")
     # Utilisez le curseur pour exécuter une commande SQL de création de base de données
    create_database_query = f"CREATE DATABASE {database_name}"
    cursor.execute(create_database_query)
    print(f"La base de données '{database_name}' a été créée avec succès.")

# Fermez le curseur et la connexion
cursor.close()
conn.close()

In [ ]:
import csv

In [ ]:
# Chemin vers le fichier CSV
csv_file_path = "Produits_-_Feuille_1.csv"

# Établir une connexion à la base de données
conn = mysql.connector.connect(
    host=host,
    user=user,
    password=password,
    database=database_name
)

# Créer un curseur pour exécuter des requêtes SQL
cursor = conn.cursor(buffered=True)

# Lecture du fichier CSV et insertion des données dans la table
with open(csv_file_path, "r", newline="") as csv_file:
    csv_reader = csv.reader(csv_file)
    en_tetes = next(csv_reader) # Enregistrer et Ignorer la première ligne si elle contient les en-têtes
    csv_reader = list(csv_reader)

for row in csv_reader:

    # Insérer les données dans la table MySQL
    insert_conditions = "INSERT IGNORE INTO courses.conditions (contenant_produit) VALUES (%s)"
    # Remplacez "nom_de_la_table" et les colonnes par les valeurs appropriées

    # Exécution de la requête d'insertion
    cursor.execute(insert_conditions, (row[3],))

    # Insérer les données dans la table MySQL
    insert_famille_article = "INSERT IGNORE INTO courses.famille_article (famille_produit) VALUES (%s)"
    # Remplacez "nom_de_la_table" et les colonnes par les valeurs appropriées

    # Exécution de la requête d'insertion
    cursor.execute(insert_famille_article, (row[2],))

    select_id_condition = f"SELECT id FROM conditions WHERE contenant_produit = %s"

    cursor.execute(select_id_condition, (row[3],))

    conditions_id = cursor.fetchone()[0]

    # Vide le curseur
    cursor.fetchone() 

    select_id_famille_article = f"SELECT id FROM famille_article WHERE famille_produit = %s"

    cursor.execute(select_id_famille_article, (row[2],))

    famille_article_id = cursor.fetchone()[0]

    cursor.fetchone()
    
    # Insérer les données dans la table MySQL
    insert_produit = "INSERT INTO courses.produit (code_article, libelle_article, famille_article_id, condition_id, pu_ht) VALUES (%s, %s, %s, %s, %s)"
    # Remplacez "nom_de_la_table" et les colonnes par les valeurs appropriées

    # Exécution de la requête d'insertion
    cursor.execute(insert_produit, (row[0],row[1],famille_article_id,conditions_id,row[4]))

# Valider les modifications dans la base de données
conn.commit()

# Fermer le curseur et la connexion
cursor.close()
conn.close()

print("Les données du fichier CSV ont été insérées avec succès dans la base de données.")

In [ ]:
import pandas as pd

In [22]:
# Lecture Base
import mysql.connector

# Remplacez les valeurs suivantes par les informations de connexion à votre serveur MySQL
host = "localhost" # L'hôte du serveur MySQL
user = "root"  # Votre nom d'utilisateur MySQL
password = "root"  # Votre mot de passe MySQL
database_name = "courses"  # Le nom de la nouvelle base de données

# help(cursor.execute)

# Établir une connexion à la base de données
conn = mysql.connector.connect(
    host=host,
    user=user,
    password=password,
    database=database_name
)

# Créer un curseur pour exécuter des requêtes SQL
cursor = conn.cursor(buffered=True)     # "Buffered = True" pour l'auto fermeture

# Lire les données dans la table MySQL produit
select_id_condition = f"SELECT * FROM produit"

# Exécution de la requête
cursor.execute(select_id_condition)

Info_Recuperees = cursor.fetchall() ###############""" Récupère toutes les données"

#******************************** Traitement Histo :
Donnees_Famille =()
Select_Donnees_Famille = f"SELECT DISTINCT famille_produit FROM famille_article"
cursor.execute(Select_Donnees_Famille)
Select_Donnees_Famille = cursor.fetchall() ###############""" Récupère toutes les données"

for i in range(Select_Donnees_Famille) :
    Donnees_Famille[1,i] = Info_Recuperees.count(Select_Donnees_Famille.)


# Valider les modifications dans la base de données
conn.commit()

# Fermer le curseur et la connexion
cursor.close()
conn.close()

TypeError: 'list' object cannot be interpreted as an integer